commit

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -54,5 +54,25 @@ pipeline {
                 }
             }
         }
+        stage('stop old container'){
+            steps{
+                sh "docker stop ${CONTAINER_NAME} || true"
+                sh "docker rm ${CONTAINER_NAME} || true"
+            }
+        }
+        stage('Run Docker Container') {
+            steps{
+                sh "docker run -d -p ${PORT}:8080 --name ${CONTAINER_NAME}
+                ${DOCKER_IMAGE}:${DOCKER_TAG}"
+            }
+        }
+        post{
+            success{
+                echo 'pipeline completed successfully.'
+            }
+            failure{
+                echo 'pipline failed. please check the logs for details.'
+            }
+        }
     }
 }
