commit

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,78 +1,184 @@
+// pipeline {
+//     agent any
+
+//     environment {
+//         DOCKER_IMAGE = 'surajprakash1/jenkins_devops'
+//         DOCKER_TAG = 'latest'
+//         CONTAINER_NAME = 'jenkins_devops_container'
+//         PORT = '8080'
+//     }
+
+//     stages {
+
+//         stage('Clone Code') {
+//             steps {
+//                 git branch: 'main',
+//                 url: 'https://github.com/surajprakash3/jenkins-devops1.git'
+//             }
+//         }
+
+//         stage('Install Dependencies') {
+//             steps {
+//                 sh 'npm install'
+//             }
+//         }
+
+//         stage('Run Test Cases') {
+//             steps {
+//                 sh 'npm test'
+//             }
+//         }
+
+//         stage('Build Docker Image') {
+//             steps {
+//                 sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
+//             }
+//         }
+
+//         stage('Push Docker Image') {
+//             steps {
+//                 withCredentials([usernamePassword(
+//                     credentialsId: 'dockerhub',
+//                     usernameVariable: 'DOCKER_USERNAME',
+//                     passwordVariable: 'DOCKER_PASSWORD'
+//                 )])
+//                 {
+//                     sh "
+//                     echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
+//                     docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
+//                     "
+
+
+//                     // sh "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
+//                     // sh "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}"
+//                 }
+//             }
+//         }
+//         stage('stop old container'){
+//             steps{
+//                 sh "docker stop ${CONTAINER_NAME} || true"
+//                 sh "docker rm ${CONTAINER_NAME} || true"
+//             }
+//         }
+//         stage('Run Docker Container') {
+//             steps{
+//                 sh "docker run -d -p ${PORT}:8080 --name ${CONTAINER_NAME}
+//                 ${DOCKER_IMAGE}:${DOCKER_TAG}"
+//             }
+//         }
+//         post{
+//             success{
+//                 echo 'pipeline completed successfully.'
+//             }
+//             failure{
+//                 echo 'pipline failed. please check the logs for details.'
+//             }
+//         }
+//     }
+// }
+
 pipeline {
-    agent any
+agent any
 
-    environment {
-        DOCKER_IMAGE = 'surajprakash1/jenkins_devops'
-        DOCKER_TAG = 'latest'
-        CONTAINER_NAME = 'jenkins_devops_container'
-        PORT = '8080'
-    }
+tools {
+nodejs 'Node22'
+}
 
-    stages {
+environment {
+DOCKER_IMAGE = 'surajprakash1/jenkins_devops'
+DOCKER_TAG = 'latest'
+CONTAINER_NAME = 'jenkins_devops_container'
+PORT = '8080'
+}
 
-        stage('Clone Code') {
-            steps {
-                git branch: 'main',
-                url: 'https://github.com/surajprakash3/jenkins-devops1.git'
-            }
-        }
+stages {
 
-        stage('Install Dependencies') {
-            steps {
-                sh 'npm install'
-            }
-        }
+stage('Clone Code') {
+steps {
+git branch: 'main',
+url: 'https://github.com/surajprakash3/jenkins-devops1.git'
+}
+}
 
-        stage('Run Test Cases') {
-            steps {
-                sh 'npm test'
-            }
-        }
+stage('Install Dependencies') {
+steps {
+sh '''
+node -v
+npm -v
+npm cache clean --force
+npm install
+'''
+}
+}
 
-        stage('Build Docker Image') {
-            steps {
-                sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
-            }
-        }
+stage('Run Test Cases') {
+steps {
+sh 'npm test'
+}
+}
 
-        stage('Push Docker Image') {
-            steps {
-                withCredentials([usernamePassword(
-                    credentialsId: 'dockerhub',
-                    usernameVariable: 'DOCKER_USERNAME',
-                    passwordVariable: 'DOCKER_PASSWORD'
-                )])
-                {
-                    sh "
-                    echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
-                    docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
-                    "
+stage('Build Docker Image') {
+steps {
+sh """
+docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
+"""
+}
+}
 
+stage('Push Docker Image') {
+steps {
+withCredentials([
+usernamePassword(
+credentialsId: 'dockerhub',
+usernameVariable: 'DOCKER_USERNAME',
+passwordVariable: 'DOCKER_PASSWORD'
+)
+]) {
+sh """
+echo \$DOCKER_PASSWORD | docker login -u \$DOCKER_USERNAME --password-stdin
+docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
+"""
+}
+}
+}
 
-                    // sh "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
-                    // sh "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}"
-                }
-            }
-        }
-        stage('stop old container'){
-            steps{
-                sh "docker stop ${CONTAINER_NAME} || true"
-                sh "docker rm ${CONTAINER_NAME} || true"
-            }
-        }
-        stage('Run Docker Container') {
-            steps{
-                sh "docker run -d -p ${PORT}:8080 --name ${CONTAINER_NAME}
-                ${DOCKER_IMAGE}:${DOCKER_TAG}"
-            }
-        }
-        post{
-            success{
-                echo 'pipeline completed successfully.'
-            }
-            failure{
-                echo 'pipline failed. please check the logs for details.'
-            }
-        }
-    }
+stage('Stop Old Container') {
+steps {
+sh """
+docker rm -f ${CONTAINER_NAME} || true
+"""
+}
+}
+
+stage('Run New Container') {
+steps {
+sh """
+docker run -d \
+--name ${CONTAINER_NAME} \
+-p ${PORT}:8080 \
+${DOCKER_IMAGE}:${DOCKER_TAG}
+"""
+}
+}
+
+stage('Verify Deployment') {
+steps {
+sh 'docker ps'
+}
+}
+}
+
+post {
+success {
+echo 'Pipeline executed successfully 🚀'
+}
+
+failure {
+echo 'Pipeline failed ❌ Check logs'
+}
+
+always {
+echo 'Pipeline finished'
+}
+}
 }
